config/routes.rb
Progmr::Application.routes.draw do
  root :to => "posts#index"
  match 'signup' => 'users#signup'
  match 'doSignup' => 'users#doSignup'

  match 'login' => 'users#login', :as => :login
  match 'doLogin' => 'users#doLogin'

  match 'logout' => 'users#logout'

  match 'posts/vote/:id/:up_or_down' => 'posts#vote', :as => :post_vote

  match 'comment/destroy/:comment_id' => 'comments#destroy', :as => :destroy_comment
  resources :posts, :except => [:destroy] do
    resources :comments
  end

  match 'p/:id' => 'posts#show', :as => :short_post_link

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :post_id, :parent_id
  belongs_to :post
  belongs_to :user

  validates :post, :presence => true
  validates :content, :presence => true, :length => {:minimum => 3}

  has_ancestry
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :login_required

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(:parent_id => params[:parent_id])
    respond_to do |format|
      format.js
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    @comment.user_id = current_user.id
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@comment.post_id.to_s(36)), notice: (t :commentSuccessfulylAdded)}
        format.js
      end
    else
      respond_to do |format|
        #format.html { redirect_to post_path(@comment.post_id.to_s(36))}
        format.json { render :json => @comment.errors }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    if current_user.id == @comment.user_id
      @comment.destroy
      respond_to do |format|
        format.js
      end
    else
      render :text => "422 You're Not Allowed to delete this comment!", :status => 422
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, childs|
      render(comment) + content_tag(:div, nested_comments(childs), :class => "nested nestedComment-#{comment.id}" )
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="row comment comment-<%= comment.id %>">
    <div class="span9">
        <%= markdown(comment.content) %>
        <div class="metainfo">
            <%= comment.user.username %> |
            <%= link_to (t :reply), new_post_comment_path(@post, :parent_id => comment), :remote => true %>
            <% if current_user && current_user.id == comment.user_id %>
             | <%= link_to (t :delete), destroy_comment_path(comment.id), :remote => true %>
            <% end %>
        </div>
    </div>
</div>

app/views/comments/_form.html.erb
<div class="row <%= "nested commentForm-#{@comment.parent_id}" if @comment.parent %>">
    <div class="span9">
        <%= form_for [@post, @comment], :remote => true do |f| %>
            <%= f.text_area :content, :class => "span9" %>
            <%= f.hidden_field :parent_id %>
            <%= f.submit (t :submitComment), :class => "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/comments/create.js.erb
<% if @comment.parent %>
$(".commentForm-<%= @comment.parent_id %>").hide();
$(".nestedComment-<%= @comment.parent_id %>").prepend("<%= j render(@comment) %>").hide().fadeIn();
<% else %>
$(".commentForm").hide();
$(".comments").prepend("<%= j render(@comment) %>").hide().fadeIn();
<% end %>

app/views/comments/destroy.js.erb
$(".comment-<%= @comment.id %>").hide('slow');

app/views/comments/new.html.erb
<h2><%= t :addComment %></h2>
<%= render @post %>
<%= render @comment.parent if @comment.parent%>
<%= render "form" %>

app/views/comments/new.js.erb
$(".comment-<%= @comment.parent_id %>").append("<%= j render("form"); %>");