config/routes.rb
Progmr::Application.routes.draw do
  root :to => "posts#index"
  match 'signup' => 'users#signup'
  match 'doSignup' => 'users#doSignup'

  match 'login' => 'users#login', :as => :login
  match 'doLogin' => 'users#doLogin'

  match 'logout' => 'users#logout'

  match 'posts/vote/:id/:up_or_down' => 'posts#vote', :as => :post_vote

  match 'comment/destroy/:comment_id' => 'comments#destroy', :as => :destroy_comment
  resources :posts, :except => [:destroy] do
    resources :comments
  end

  match 'p/:id' => 'posts#show', :as => :short_post_link

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :url

  belongs_to :user
  belongs_to :major_tag, :class_name => "Tag"
  belongs_to :minor_tag, :class_name => "Tag"
  belongs_to :extra_tag, :class_name => "Tag"

  has_many :post_votes
  has_many :voters, :through => :post_votes, :source => :user

  has_many :comments

  validates :title, :presence => true
  validates :content, :presence => true
  validates :major_tag, :presence => true
  validates :url, :format => URI::regexp(%w(http https)), :allow_blank => true

  def prepare_tags(major_tag_name, minor_tag_name = nil, extra_tag_name = nil)
    major = Tag.find_or_create_by_name(major_tag_name) if not major_tag_name.blank?
    minor = Tag.find_or_create_by_name(minor_tag_name) if not minor_tag_name.blank?
    extra = Tag.find_or_create_by_name(extra_tag_name) if not extra_tag_name.blank?
    self.major_tag = major if major
    self.minor_tag = minor if minor
    self.extra_tag = extra if extra
  end
end

app/controllers/posts_controller.rb
require 'uri'
class PostsController < ApplicationController
  before_filter :login_required, :except => [:index, :show]

  def index
    if current_user
      @posts = Post.all(
          :include => [:major_tag, :minor_tag, :extra_tag],
          :joins => [:user,
                     "LEFT OUTER JOIN post_votes ON post_votes.post_id = posts.id AND post_votes.user_id = #{current_user.id}"],
          :select => "posts.*, users.username, post_votes.vote", :order => "created_at DESC")
    else
      @posts = Post.all(:order => "created_at DESC")
    end
  end

  def show
    @post = Post.find(params[:id].to_i(36))
    if current_user
      @comment = Comment.new
      @comment.post = @post
      postVote = PostVote.where("user_id = ? AND post_id = ?", current_user.id, @post.id).first
      @postvote = postVote.vote if postVote
    end
  end

  def new
    @post = Post.new
  end

  def create
    # tags
    @post = Post.new(params[:post])
    @post.user = current_user
    @post.prepare_tags(params[:major_tag], params[:minor_tag], params[:extra_tag])

    if @post.save
        @post.user.increment!(:posts_karma)
        redirect_to post_path(@post.id.to_s(36)), notice: (t :postSuccessfullyCreated)
    else
        # Should be refactored to a more ruby idiomatic way!
        render action: "new"
    end
  end

  def vote
    @postId = params[:id].to_i(36)
    @direction = params[:up_or_down] == "up" ? "up" : "down"

    postVote = PostVote.where("user_id = ? AND post_id = ?", current_user.id, @postId).first
    if postVote
      # if user already voted, destroy his vote
      orgVoteDirection = postVote.vote
      postVote.destroy
    end

    if postVote && ((@direction == "up" && orgVoteDirection == true) || (@direction == "down" && orgVoteDirection == false))
      # if clicked vote direction equals the previous one, then the user just want to remove his vote
      @status = "Removed"
    else
      # new vote or
      # the user clicked on vote direction that's different than the previous one

      post = Post.select("user_id, votes").find(@postId)

      if post.user_id == current_user.id
        @status = "CreatorAndVoterAreSame"
      else
        postVote = PostVote.new
        postVote.user_id = current_user.id
        postVote.post_id = @postId
        if @direction == "up"
          postVote.vote = true
          @status = "UpVoted"
        else
          postVote.vote = false
          @status = "DownVoted"
        end
        postVote.save
      end
    end
    #retrive updated votes
    @votes = Post.select("votes").find(@postId).votes

    respond_to do |format|
      format.js #render vote.js.erb
    end
  end

  def edit
    @post = Post.find(params[:id].to_i(36))

    if @post.user_id != current_user.id
      render :text => "422 You're Not Allowed to edit this post!", :status => 422
      return
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.prepare_tags(params[:major_tag], params[:minor_tag], params[:extra_tag])

    if @post.user_id != current_user.id
      render :text => "422 You're Not Allowed to edit this post!", :status => 422
      return
    end

    if @post.update_attributes(params[:post])
        redirect_to post_path(@post.id.to_s(36)), notice: 'Post was successfully updated.'
    else
      render action: "edit"
    end
  end

end

app/helpers/posts_helper.rb
require 'uri'
module PostsHelper
  def isImg?

  end
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <div class="alert-error">
        <h3><%= t :pleaseFixTheFollowingErrors %></h3>
        <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="control-group">
    <%=  f.label :title, :class => "control-label" %>
    <div class="controls">
        <%=  f.text_field :title, :class => "span9" %>
    </div>
</div>

<section class="optional">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <%=  f.label :url, :class => "control-label" %>
                <div class="controls">
                    <%=  f.text_field :url, :class => "span5" %>
                </div>
            </div>
        </div>
        <div class="span4">
            <small>هذا الحقل إختياري، بإمكانك استخدامه  للإشارة إلى محتوى خارجي، مثل مقالة في موقع آخر أو لملف PDF.</small>
        </div>
    </div>
</section>

<div class="control-group">
    <%=  f.label :content, :class => "control-label" %>
    <div class="controls">
        <%=  f.text_area :content, :class => "span9" %>
    </div>
</div>

<div class="row">
    <div class="span3">
        <%= f.label :major_tag %>
    </div>
    <div class="span3">
        <%= f.label :minor_tag %>
    </div>
    <div class="span3 extraTagLabel">
        <%= f.label :extra_tag %>
    </div>
</div>
<div class="row">
    <div class="span3">
        <%=  text_field_tag :major_tag, (@post.major_tag.name if @post.major_tag), :class => "input-block-level" %>
    </div>
    <div class="span3">
        <%=  text_field_tag :minor_tag, (@post.minor_tag.name if @post.minor_tag), :class => "input-block-level" %>
    </div>
    <div class="span3">
        <a href="#" id="showExtraTag" onclick=""><%= t :needExtraTag %></a>
        <%=  text_field_tag :extra_tag, (@post.extra_tag.name if @post.extra_tag), :class => "input-block-level extraTagInput" %>
    </div>
</div>

app/views/posts/_post.html.erb
<h3><%= post.title %></h3>

app/views/posts/edit.html.erb
<h3><%= t :newPost %></h3>
<%= form_for @post do |f| %>
    <%= render 'form', :f => f %>
    <div class="control-group">
        <%=  f.submit (t :newPostSubmit), :class => "btn btn-primary" %>
    </div>
<% end %>
<script>
    $(".extraTagInput, .extraTagLabel").hide();
    $("#showExtraTag").click(function(e) {
        $('#showExtraTag').hide('fast');
        $('.extraTagInput, .extraTagLabel').show('slow');
        e.preventDefault();
    });
</script>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<section class="post post-<%= post.id%>">
<div class="row">
    <div class="span1 voteColumn">
        <%= link_to raw("&#9650;"), post_vote_path(post.id.to_s(36), :up), remote: true, :class => "voteLinkUp " + ( (current_user && post.vote == 1) ? "voted":"") %>
        <div class="postVotes"><%= post.votes %></div>
        <%= link_to raw("&#9660;"), post_vote_path(post.id.to_s(36), :down), remote: true, :class => "voteLinkDown " + ( (current_user && post.vote == 0) ? "voted":"") %>
    </div>
    <div class="span8">
        <div class="row">
            <div class="span8">
                <div class="postTitle">
                    <% if post.url.blank? %>
                        <%= link_to post.title, short_post_link_path(post.id.to_s(36)) %>
                    <% else %>
                        <%= link_to post.title, post.url %><span class="url"><%= URI.parse(post.url).host %></span>
                        <div class="urlContent">
                            <%= post.content[0,250] %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="row metainfo">
            <div class="span8">
                <div><%= post.major_tag.name %> |&nbsp;</div>
                <div><%= (t :before) + " " + time_ago_in_words(post.created_at) %> |&nbsp;</div>
                <div><%= post.user.username %> |&nbsp;</div>
                <div><%= link_to (t :comments) + ": " + post.comments.count.to_s, short_post_link_path(post.id.to_s(36)) %>&nbsp;</div>
            </div>
        </div>
    </div>
</div>
</section>
<% end %>
<script>
<% if not current_user %>
$(".voteLinkUp, .voteLinkDown").click(function(e){
   alert("<%= t :pleaseLoginToVote %>");
});
<% end %>
</script>

app/views/posts/new.html.erb
<h3><%= t :newPost %></h3>
<%= form_for @post do |f| %>
    <%= render 'form', :f => f %>
    <div class="control-group">
        <%=  f.submit (t :newPostSubmit), :class => "btn btn-primary" %>
    </div>
<% end %>
<script>
    $(".extraTagInput, .extraTagLabel").hide();
    $("#showExtraTag").click(function(e) {
        $('#showExtraTag').hide('fast');
        $('.extraTagInput, .extraTagLabel').show('slow');
        e.preventDefault();
    });
</script>

app/views/posts/show.html.erb
<div class="post post-<%= @post.id%>">
<div class="row">
    <div class="span1 voteColumn">
        <%= link_to raw("&#9650;"), post_vote_path(@post.id.to_s(36), :up), remote: true, :class => "voteLinkUp " + ( (current_user && @postvote == true) ? "voted":"") %>
        <div class="postVotes"><%= @post.votes %></div>
        <%= link_to raw("&#9660;"), post_vote_path(@post.id.to_s(36), :down), remote: true, :class => "voteLinkDown " + ( (current_user && @postvote == false) ? "voted":"") %>
    </div>
    <div class="span8">
        <div class="row">
            <div class="span8">
                <div class="postTitle">
                    <% if @post.url.blank? %>
                        <%= @post.title %>
                    <% else %>
                        <%= link_to @post.title, @post.url %><span class="url"><%= URI.parse(@post.url).host %></span>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="row metainfo">
        <div class="span8">
            <%= @post.user.username %> |
            <%= t :comments %>:<%= @post.comments.count %>
            <% if current_user && @post.user_id == current_user.id %>
                | <%=  link_to (t :edit), edit_post_path(@post.id.to_s(36)) %>
            <% end %>
        </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="span9 postContent">
        <%= markdown(@post.content) %>
    </div>
</div>

<section class="commentsSection">

<div class="row">
    <div class="span9">
        <h2><%= t :comments %></h2>
    </div>
</div>

<% if current_user %>
<section class="commentForm">
<%= render "comments/form" %>
</section>
<% end %>

<section class="comments">
<%= nested_comments @post.comments.arrange(:order => :created_at) %>
</section>

</section>
</div>

app/views/posts/vote.js.erb
$(".post-<%= @postId %> .voteLinkUp").removeClass("voted");
$(".post-<%= @postId %> .voteLinkDown").removeClass("voted");
$(".post-<%= @postId %> .postVotes").text("<%= @votes %>");

<% if @status == "CreatorAndVoterAreSame" %>
    alert("<%= t :youCantVoteYourOwnPost %>");
<% elsif @status == "UpVoted" %>
    $(".post-<%= @postId %> .voteLinkUp").addClass("voted");
    $(".post-<%= @postId %> .postVotes").text("<%= @votes %>");
<% elsif @status == "DownVoted" %>
    $(".post-<%= @postId %> .voteLinkDown").addClass("voted");
    $(".post-<%= @postId %> .postVotes").text("<%= @votes %>");
<% end %>