config/routes.rb
Progmr::Application.routes.draw do
  root :to => "posts#index"
  match 'signup' => 'users#signup'
  match 'doSignup' => 'users#doSignup'

  match 'login' => 'users#login', :as => :login
  match 'doLogin' => 'users#doLogin'

  match 'logout' => 'users#logout'

  match 'posts/vote/:id/:up_or_down' => 'posts#vote', :as => :post_vote

  match 'comment/destroy/:comment_id' => 'comments#destroy', :as => :destroy_comment
  resources :posts, :except => [:destroy] do
    resources :comments
  end

  match 'p/:id' => 'posts#show', :as => :short_post_link

end

app/views/layouts/_right_side.html.erb
<h3>فكرة الموقع</h3>
بوابة معرفية للمبرمجين، تحتوي على أسئلة و تمارين برمجية بالإضافة إلى
مقالات متنوعة و شبكة إجتماعية تضم نخبة من المبرمجين العرب

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Progmr</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="http://fast.fonts.com/jsapi/14ad7663-f050-4800-a989-2e51a08b9fa5.js?2"></script>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="span12">
        <div class="topBar">
            &nbsp;
        </div>
        </div>
    </div>

    <div class="row header">
        <div class="span5">
            <h1>{ <%= link_to (t :siteName), root_path %> }</h1>
        </div>
        <div class="span7 actions">
            <% if current_user %>
                <div>
                <span><%= current_user.username %> |&nbsp;</span>
                <span> <%= image_tag "user_karma.png" %><%= current_user.posts_karma + current_user.comments_karma %> |&nbsp;</span>
                <span> <%= link_to (t :newPost), new_post_path %> |&nbsp;</span>
                <span> <%= link_to (t :logout), logout_path %></span>
                </div>
            <% else %>
                <%= link_to (t :signup), signup_path %> |
                <%= link_to (t :login), login_path %>
            <% end %>
        </div>
    </div>

    <% if flash[:notice] %>
    <div class="row alert-box notice">
        <div class="span12">
            <div class="fade in">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h3>
                    <%= flash[:notice] %>
                </h3>
            </div>
        </div>
    </div>
    <script>
    setTimeout(function() { $(".notice").hide(); }, 2500);
    </script>
    <% end %>

    <% if flash[:warning] %>
        <div class="row alert-box warning">
            <div class="span12">
                <div class="fade in">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <h3>
                        <%= flash[:warning] %>
                    </h3>
                </div>
            </div>
        </div>
    <% end %>

    <div class="row">
        <div class="span9">
        <div class="content">
            <%= yield %>
        </div>
        </div>
        <div class="span3">
        <div class="side">
            <%= render 'layouts/right_side' %>
        </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-63613-13']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>


</body>
</html>